### ISSUE TITLE
Struggling with the Racket example

### ISSUE THREAD

**Issue by krrrcks** [lambrospetrou/aws-lambda-binary#2]
I tried the Racket example and fiddled for several hours. But I was not able to get it running. I always ran into a "time out" situation or it seemed that the Racket backend never got called. I also tried with the wrapper code from your blog but was not able to get it running. I am on Racket 6.12 and used AWS Lambda at Frankfurt location (eu-central-1). Did something change in the infrastructure or am I too stupid to get things going?

**Comment by lambrospetrou** [comment]
Hello @krrrcks it's not your fault. I get the same timeout with Racket but if I try with the builtin linux command `cat`, or with a custom built Go program that just echo-es the input (like the Racket example does) it works fine.

It seems that the latest AWS Lambda container, `Amazon Linux AMI release 2017.03`, changed something which makes the Racket binaries not executable. I am sure that fiddling around with a box of this version and finding the right arguments to statically compile the Racket executable for the new Amazon Linux should work.

The library works fine though.

**Comment by lambrospetrou** [comment]
Actually it seems that it is in Racket that something broke. As I said I tried the following Go code and it works perfectly:

```
package main
import ("fmt")
func main() {
        s := ""
        for {
                fmt.Scanf("%s", &s)
                fmt.Println(s);
        }
}
```

In Racket the following code timeouts, and after adding some logging I found out that the NodeJS wrapper is stuck while reading from the `stdout` of the spawned process.

```
;; Code that timeouts
#lang racket/base

(define (execute-logic data)
  (display (format "data: ~a~%" data)))

(define (loop)
  (execute-logic (read-line))
  (loop))
(loop)
```

If we remove the looping, and just read from stdin once and print to the stdout, it works fine, which means it's not a binary problem either.

```
;; Code that DOES NOT timeout
#lang racket/base

(define (execute-logic data)
  (display (format "data: ~a~%" data)))
(execute-logic (read-line))
```

The above makes me thinking that something in Racket blocks the process.

**Comment by lambrospetrou** [comment]
Found the problem ;p

It seems that the Racket default standard output port does not flush what we write and therefore the NodeJS process is stuck at waiting to read data. If we force the Racket to flush its output everything works fine.

It would be interesting to see when this change was introduced or if it **just** happened to work in the past when I firstly did it.

The code that works is as follows (note the `flush-output` line).

```
#lang racket/base

(define (execute-logic data)
  (display (format "data: ~a~%" data))
  (flush-output))

(define (loop)
  (execute-logic (read-line))
  (loop))
(loop)
```
