### ISSUE TITLE
Issue in Executing Binary Generated from C in Lambda

### ISSUE THREAD

**Issue by nbibin001** [lambrospetrou/aws-lambda-binary#3]
Hello, I was able to run the examples in my Lambda function. But I then I wanted to run my own binary file which is generated from a C file. So I made some changes to the Makefile and also in the wrapper.js file as below. But when I was running the Lambda function, when it calls the binary I am getting an error "Process exited before completing request". Could you please help, I am not able to figure out what am I doing wrong. Please let me know if you need more details.

![image](https://user-images.githubusercontent.com/15659590/56860405-524dfe80-6964-11e9-9fa6-f7845a30cd50.png)
![image](https://user-images.githubusercontent.com/15659590/56860410-64c83800-6964-11e9-85de-b917b077ce1f.png)
![image](https://user-images.githubusercontent.com/15659590/56860455-b07ae180-6964-11e9-8d82-f2794cddfaa3.png)

**Comment by lambrospetrou** [comment]
The binary is probably not a valid executable.
Try adding `withLogging: true` to the `options` object and see if there is a helpful error message being logged.

Also make sure that the executable is built in a way that can run on an EC2 with Amazon Linux.

**Comment by lambrospetrou** [comment]
Closing this due to no response from the author.
